apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pvc
  namespace: unifi
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pvc-mongodb
  namespace: unifi
spec:
  storageClassName: nfs-nolock
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
